---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: risk-assessment
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "quay.io/guimou/xraylab-risk-assessment:rhtr_v1.4"
      importPolicy: {}
      referencePolicy:
        type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: image-generator
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "quay.io/guimou/xraylab-image-generator:rhtr_v1.4"
      importPolicy: {}
      referencePolicy:
        type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: image-server
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "quay.io/guimou/xraylab-image-server:rhtr_v1.4"
      importPolicy: {}
      referencePolicy:
        type: Source
