kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "kafka-producer:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: "registry.access.redhat.com/ubi8/python-38:latest"
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/red-hat-data-services/jumpstart-library"
    contextDir: patterns/Inference-to-kafka/src/kafka_producer_app
  triggers:
    - type: ConfigChange
  runPolicy: Serial
