apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafana-datasource
spec:
  datasources:
    - basicAuthUser: internal
      access: proxy
      editable: true
      isDefault: true
      secureJsonData:
        httpHeaderValue1: "Bearer BEARER_TOKEN"
      name: prometheus
      url: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"
      jsonData:
        httpHeaderName1: "Authorization"
        timeInterval: 5s
        tlsSkipVerify: true
      type: prometheus
  name: grafana-prometheus-datasource.yaml
