---
# This is the component that runs in the Core and listens to incoming Kafka events
# to write them into a PostgreSQL database so that they can be queried to create the dashboards.

- name: Deploy Kafka to PostgreSQL bridge
  k8s:
    state: present
    resource_definition: "{{ item }}"
    namespace: "{{ install_namespace }}"
  with_items:
    - "{{ lookup('file', 'events_service/is_events_service.yaml') | from_yaml_all }}" # ImageStream for the event service
    - "{{ lookup('file', 'events_service/bc_events_service.yaml') | from_yaml_all }}" # BuildConfiguration for the event service
    - "{{ lookup('file', 'events_service/dc_events_service.yaml') | from_yaml_all }}" # Deployment Configuration for the event service
