---
# For calculating the toll and pollution fee, there are two cases that we have covered:
#   When any vehicle enters the ULEZ, a certain fee (aka toll fee) must be applied to that vehicle
#   If the vehicle model is too old (older than 2014), apply addition fee (aka pollution fee) on that vehicle

- name: Deploy load generator
  k8s:
    state: present
    src: "{{ item }}"
  with_items:
    - fee_calculation/is_fee_calculation.yaml
    - fee_calculation/bc_fee_calculation.yaml
    - fee_calculation/cronjob_fee_calculation.yaml
