---
# This is the component that injects car images into the pipeline.

- name: Deploy load generator
  k8s:
    state: present
    src: "{{ item }}"
  with_items:
    - generator/obc_dataset_generator.yaml # Bucket to store the images dataset
    - generator/is_generator.yaml # ImageStream for the load generator
    - generator/bc_generator.yaml # BuildConfiguration to create the load generator image
    - generator/dc_generator.yaml # Deployment Configuration for the load generator
