---
# This component presents an API that you can query with an image and returns the infered licence plate number.

- name: Deploy license plate reader service
  k8s:
    state: present
    src: "{{ item }}"
  with_items:
    - lpr_service/is_lpr_service.yaml # ImageStream for the LPR service
    - lpr_service/bc_lpr_service.yaml # BuildConfiguration for the LPR service
    - lpr_service/dc_lpr_service.yaml # Deployment Configuration for the LPR service
    - lpr_service/svc_lpr_service.yaml # Service to access the LPR service
