---
# This component presents an API that you can query with an image and returns the infered licence plate number.

- name: Deploy license plate reader service
  k8s:
    state: present
    resource_definition: "{{ item }}"
    namespace: "{{ install_namespace }}"
  with_items:
    - "{{ lookup('file', 'lpr_service/is_lpr_service.yaml') | from_yaml_all }}" # ImageStream for the LPR service
    - "{{ lookup('file', 'lpr_service/bc_lpr_service.yaml') | from_yaml_all }}" # BuildConfiguration for the LPR service
    - "{{ lookup('file', 'lpr_service/dc_lpr_service.yaml') | from_yaml_all }}" # Deployment Configuration for the LPR service
    - "{{ lookup('file', 'lpr_service/svc_lpr_service.yaml') | from_yaml_all }}" # Service to access the LPR service
