apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: edge-kafka
  labels:
    app: edge-kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      inter.broker.protocol.version: '2.6'
      log.message.format.version: '2.6'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
      class: ocs-storagecluster-ceph-rbd
    version: 2.6.0
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
      class: ocs-storagecluster-ceph-rbd
